name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create dummy go.sum if not exists
      run: |
        if [ ! -f go.sum ]; then
          echo "# dummy go.sum" > go.sum
        fi

    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: limi188/easy-tvframework-go:latest
        build-args: |
          TARGETOS=linux
          TARGETARCH=amd64
