# 使用 Golang 官方镜像
FROM golang:1.18-alpine AS builder

# 设置工作目录
WORKDIR /go/src/app

# 复制当前目录内容到容器中
COPY . .

# 下载依赖并构建 Go 程序，生成二进制文件
RUN go mod tidy && \
    go build -o easy-tv ./cmd/main.go  # 确保路径正确

# 使用一个轻量级的镜像来运行应用
FROM alpine:latest  

# 安装必要的运行时依赖
RUN apk --no-cache add ca-certificates

# 将编译后的二进制文件复制到新镜像
COPY --from=builder /go/src/app/easy-tv /usr/local/bin/

# 设置应用的默认命令
CMD ["easy-tv"]
