name: Build Windows EXE and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build Windows Executable
      run: go build -o easy-tvframework-go.exe

    - name: Upload Windows EXE to Release
      uses: softprops/action-gh-release@v1
      with:
        files: easy-tvframework-go.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
